version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:8.16
    working_directory: ~/project/
    steps:
      - checkout
      - run:
          name: Install npm modules
          command: cd server && npm i

      - run:
          name: Run test cases
          command: cd server && npm run test


workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
